schema {
  query: Query
}

type Query {
  """
  Returns information about a Chrome extension based on it's ID and language (defaults to "en").
  """
  chromeExtension(id: String!): ChromeExtension
  """
  Returns information about a list of Chrome extension ids.
  """
  chromeExtensions(ids: [String!]!): [ChromeExtension]!

  """
  Returns information about a Firefox addon based on it's ID/GUID/slug.
  """
  firefoxAddon(id: String!): FirefoxAddon
  """
  Returns information about a list of Firefox addon ID/GUID/slugs.
  """
  firefoxAddons(ids: [String!]!): [FirefoxAddon]!

  """
  Returns information about an Edge addon based on it's CRX ID.
  """
  edgeAddon(id: String!): EdgeAddon
  """
  Returns information about a list of Edge addon IDs.
  """
  edgeAddons(ids: [String!]!): [EdgeAddon]!
}

interface Extension {
  id: String!
  name: String!
  iconUrl: String!
  storeUrl: String!
  shortDescription: String!
  longDescription: String!
  """
  Different extension stores report users in different units (e.g., weekly active users, daily active users).

  This field is meant to be used as a generic representation of the number of users. Each type that extends this one has individual fields denoting the unit (`ChromeExtension.weeklyActiveUsers`, `FirefoxAddon.dailyActiveUsers`, etc).
  """
  users: Int!
  version: String!
  lastUpdated: String!
  rating: Float
  reviewCount: Int
  screenshots: [Screenshot!]!
}

type ChromeExtension implements Extension {
  # Extension fields

  id: String!
  name: String!
  iconUrl: String!
  storeUrl: String!
  shortDescription: String!
  longDescription: String!
  "Same as weeklyActiveUsers"
  users: Int!
  version: String!
  lastUpdated: String!
  rating: Float
  reviewCount: Int
  screenshots: [Screenshot!]!

  # Additional fields

  weeklyActiveUsers: Int!
}

type FirefoxAddon implements Extension {
  # Extension fields

  id: String!
  name: String!
  iconUrl: String!
  storeUrl: String!
  shortDescription: String!
  longDescription: String!
  "Same as dailyActiveUsers"
  users: Int!
  version: String!
  lastUpdated: String!
  rating: Float
  reviewCount: Int
  screenshots: [Screenshot!]!

  # Additional fields

  dailyActiveUsers: Int!
}

type EdgeAddon implements Extension {
  # Extension fields

  id: String!
  name: String!
  iconUrl: String!
  storeUrl: String!
  shortDescription: String!
  longDescription: String!
  "Same as activeInstallCount"
  users: Int!
  version: String!
  lastUpdated: String!
  rating: Float
  reviewCount: Int
  screenshots: [Screenshot!]!

  # Additional fields

  "Number of users shown on `microsoftedge.microsoft.com`"
  activeInstallCount: Int!
}

type Screenshot {
  """
  The screenshot's order.
  """
  index: Int!
  """
  The image's raw URL provided by the service. When screenshots are updated, this URL changes.
  """
  rawUrl: String!
  """
  URL to the image based on the index. If the raw URL changes, the `indexUrl` will remain constant, good for links in README.md files.
  """
  indexUrl: String!
}
