schema {
  query: Query
}

type Query {
  """
  Returns information about a Chrome extension based on it's ID and language (defaults to "en").
  """
  chromeExtension(id: String!): ChromeExtension
  """
  Returns information about a list of Chrome extension ids.
  """
  chromeExtensions(ids: [String!]!): [ChromeExtension]!
  """
  Returns information about a Firefox addon based on it's ID/GUID/slug.
  """
  firefoxAddon(id: String!): FirefoxAddon
  """
  Returns information about a list of Firefox addon ID/GUID/slugs.
  """
  firefoxAddons(ids: [String!]!): [FirefoxAddon]!
}

type ChromeExtension {
  id: String!
  name: String!
  iconUrl: String!
  storeUrl: String!
  shortDescription: String!
  longDescription: String!
  weeklyActiveUsers: Int!
  version: String!
  lastUpdated: String!
  rating: Float
  reviewCount: Int
  screenshots: [Screenshot!]!
}

type FirefoxAddon {
  id: String!
  name: String!
  iconUrl: String!
  storeUrl: String!
  shortDescription: String!
  longDescription: String!
  dailyActiveUsers: Int!
  version: String!
  lastUpdated: String!
  rating: Float
  reviewCount: Int
  screenshots: [Screenshot!]!
}

type Screenshot {
  """
  The screenshot's order.
  """
  index: Int!
  """
  The image's raw URL provided by the service. When screenshots are updated, this URL changes.
  """
  rawUrl: String!
  """
  URL to the image based on the index. If the raw URL changes, the `indexUrl` will remain constant, good for links in README.md files.
  """
  indexUrl: String!
}
